import { useEffect, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, Search, X, Menu, ChevronDown, Plus, Check, Bookmark, Globe2, Cpu, Zap, Radio, Send, Terminal, Copy, ExternalLink, RotateCcw, Download, MoveUpRight, CircleHelp } from 'lucide-react';
import { content, industries, searchContent, stories } from './content';
import type { Content } from './content';
import { askGuide, filterIndustries, navigate, openArticle, openDirectory, openModal, runGuideAction, saveContent, update, useSite } from './store';
import type { Filter, Section } from './store';
import { toolManifest } from './webmcp';

function IntelligenceMark({ className = '' }: { className?: string }) {
  return <svg className={`intelligence-mark ${className}`} viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="m16 2 4.2 9.8L30 16l-9.8 4.2L16 30l-4.2-9.8L2 16l9.8-4.2L16 2Z" stroke="currentColor" strokeWidth="1.5"/><path d="m7 7 9 4 9-4-4 9 4 9-9-4-9 4 4-9-4-9Z" stroke="currentColor" strokeWidth="1"/><circle cx="16" cy="16" r="3" fill="currentColor"/></svg>;
}
function Label({ children, light = false }: { children: ReactNode; light?: boolean }) { return <div className={`eyebrow ${light ? 'light' : ''}`}><span className="tiny-square"/>{children}</div>; }
function External({ href, children, className = '' }: { href: string; children: ReactNode; className?: string }) { return <a href={href} className={className} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={17}/><span className="sr-only"> (opens official site in a new tab)</span></a>; }
function SaveButton({ id, label = false }: { id: string; label?: boolean }) {
  const { shortlist } = useSite(); const saved = shortlist.includes(id);
  return <button className={label ? 'button secondary' : `save-button ${saved ? 'saved' : ''}`} aria-label={`${saved ? 'Remove' : 'Save'} ${content.find(c => c.id === id)?.title}`} aria-pressed={saved} onClick={() => { try { saveContent(id, !saved); } catch (e) { update({ lastAction: (e as Error).message }); } }}>{saved ? <Check size={17}/> : <Bookmark size={17}/>} {label && (saved ? 'Saved to collection' : 'Save to collection')}</button>;
}
const heroScenes = [
  { name: 'Intelligent machines', image: 'hero', label: 'AUTONOMY / NEXT-GENERATION THINKING', description: 'The strength to build. The intelligence to go further. Together, we’re shaping a better world.' },
  { name: 'Limitless possibility', image: 'mining', label: 'MINING / A NEW HORIZON', description: 'Big challenges call for bigger thinking. Explore the technologies moving our world forward.' },
  { name: 'A connected world', image: 'energy', label: 'ENERGY / POWERING PROGRESS', description: 'Power for the way we live. Possibilities for the way we’ll live next. The future starts here.' },
];
const innovations = [
  { icon: Cpu, title: 'Autonomous. Never standing still.', label: 'Autonomy & AI', image: '/images/mining.webp', text: 'Intelligence that moves beyond the screen. Explore autonomous hauling, robotics, and digital twins designed for the demands of the real world.', tags: ['Autonomous hauling', 'Artificial intelligence', 'Digital twins'], article: 'field-ai' },
  { icon: Zap, title: 'More ways to power progress.', label: 'Energy evolution', image: '/images/energy.webp', text: 'Meeting the world’s energy needs takes more than one solution. Explore the power systems and sustainability work behind Caterpillar’s next chapter.', tags: ['Power systems', 'Sustainability', 'Circular economy'], article: 'sustainability' },
  { icon: Radio, title: 'Connected insight. Human impact.', label: 'Connected jobsites', image: '/images/hero.webp', text: 'Equipment, information, and expertise working together. Discover how connectivity and technology help customers make better-informed decisions.', tags: ['Connectivity', 'Customer support', 'Technology'], article: 'innovation' },
];

function Header() {
  const [mobile, setMobile] = useState(false);
  const { shortlist } = useSite();
  const go = (section: Section) => { navigate(section); setMobile(false); };
  return <>
    <div className="utility-bar"><span><span className="status-dot"/> AN INDEPENDENT VISION FOR 2028</span><div><button onClick={() => openDirectory('Investors')}>Investors <ArrowUpRight size={11}/></button><button onClick={() => go('careers')}>Careers</button><button onClick={() => { const contact=content.find(c=>c.title==='Contact Us'); if(contact)openArticle(contact.id);else openDirectory('Company'); }}>Contact</button><span className="utility-language"><Globe2 size={12}/> EN / GLOBAL</span></div></div>
    <header className="site-header"><a className="wordmark" href="#home" aria-label="Caterpillar concept home" onClick={e => { e.preventDefault(); go('home'); }}><img src="/images/caterpillar-logo.png" alt="Caterpillar" width="184" height="32"/></a><nav aria-label="Main navigation" className={mobile ? 'main-nav mobile-open' : 'main-nav'}><button onClick={() => { openDirectory('Company'); setMobile(false); }}>Company <ChevronDown size={12}/></button><button onClick={() => go('industries')}>Industries</button><button onClick={() => go('innovation')}>Innovation <span className="nav-new"/></button><button onClick={() => go('sustainability')}>Sustainability</button><button onClick={() => go('news')}>News & stories</button><button className="mobile-nav-collection" onClick={() => { openModal('shortlist'); setMobile(false); }}>Your collection ({shortlist.length}) <Bookmark size={15}/></button></nav><div className="header-actions"><button className="icon-button search-trigger" onClick={() => openModal('search')} aria-label="Search website"><Search size={20}/></button><button className="icon-button collection-trigger" onClick={() => openModal('shortlist')} aria-label={`Your collection, ${shortlist.length} saved items`}><Bookmark size={18}/>{shortlist.length > 0 && <span className="badge">{shortlist.length}</span>}</button><button className="header-guide" aria-label="Open Cat Intelligence guide" onClick={() => openModal('guide')}><IntelligenceMark/> <span>Cat Intelligence</span><ArrowUpRight size={15}/></button><button className="icon-button mobile-toggle" aria-label={mobile ? 'Close navigation' : 'Open navigation'} aria-expanded={mobile} onClick={() => setMobile(!mobile)}>{mobile ? <X/> : <Menu/>}</button></div></header>
  </>;
}
function Hero() {
  const [scene, setScene] = useState(0); const active = heroScenes[scene];
  return <section id="home" className="hero" aria-labelledby="hero-title">
    {heroScenes.map((s,i) => <img key={s.image} className={`hero-image ${scene === i ? 'active' : ''}`} src={`/images/${s.image}.webp`} alt={i === 0 ? 'AI-imagined next-generation yellow Cat excavator in a dramatic basalt quarry at dusk' : i === 1 ? 'AI-imagined autonomous mining truck at sunrise' : 'AI-imagined connected energy campus at twilight'} fetchPriority={i === 0 ? 'high' : 'low'} loading={i === 0 ? 'eager' : 'lazy'}/>)}
    <div className="hero-scrim"/><div className="hero-grid" aria-hidden="true"/>
    <div className="hero-content"><Label>A CENTURY OF PROGRESS. A NEW ERA.</Label><h1 id="hero-title">BUILT FOR<br/>WHAT’S <span>NEXT.</span></h1><p key={scene} className="hero-description">{active.description}</p><div className="hero-buttons"><button className="button yellow" onClick={() => navigate('innovation')}>Explore what’s next <ArrowUpRight size={19}/></button><button className="text-button" onClick={() => navigate('company')}>The Caterpillar story <ArrowRight size={16}/></button></div></div>
    <div className="hero-coordinate"><span className="crosshair"/><span>REAL-WORLD STRENGTH.<br/>NEXT-GENERATION INTELLIGENCE.</span></div>
    <div className="hero-stamp"><span className="stamp-corner"/><span>2028<br/><small>VISION SERIES</small></span><MoveUpRight size={25}/></div>
    <div className="hero-bottom"><div className="scene-switcher" aria-label="Explore concept imagery">{heroScenes.map((s,i) => <button key={s.name} className={scene === i ? 'active' : ''} aria-pressed={scene === i} onClick={() => setScene(i)}><span>0{i+1}</span>{s.name}<i/></button>)}</div><span className="image-disclosure">AI-IMAGINED FUTURE · NOT A PRODUCT ANNOUNCEMENT</span><button className="scroll-cue" aria-label="Scroll to industries" onClick={() => navigate('industries')}><ArrowDown size={18}/></button></div>
  </section>;
}
function GuideBar() {
  const [query,setQuery] = useState('');
  function submit(e: FormEvent) { e.preventDefault(); if (query.trim()) { void askGuide(query); setQuery(''); } else openModal('guide'); }
  return <section className="guide-bar" aria-label="Caterpillar intelligent guide"><div className="guide-bar-label"><IntelligenceMark/><div><strong>A new way to explore.</strong><span>YOUR AMBITION. A SMARTER START.</span></div></div><form onSubmit={submit}><label htmlFor="hero-question" className="sr-only">Ask the Caterpillar guide</label><input id="hero-question" maxLength={1200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="What do you want to build next?"/><button type="submit" aria-label="Ask the guide"><ArrowUpRight size={22}/></button></form><button className="guide-example" onClick={() => { void askGuide('Tell me about autonomous mining'); }}>Explore autonomy <ArrowUpRight size={13}/></button><button className="guide-example" onClick={() => { void askGuide('Find careers in engineering'); }}>Find my next role <ArrowUpRight size={13}/></button></section>;
}
function Industries() {
  const { filter } = useSite();
  return <section id="industries" className="section industries-section"><div className="section-heading"><div><Label>01 / THE WORLD WE BUILD</Label><h2>BIG AMBITIONS.<br/><span className="muted">REAL-WORLD SOLUTIONS.</span></h2></div><div className="heading-aside"><p>For the work that matters.<br/>And the world that comes next.</p><button className="text-button" onClick={() => openDirectory('Industries')}>Explore all industries <ArrowUpRight size={18}/></button></div></div><div className="industry-filters" aria-label="Filter industries">{[['all','All industries'],['construction','Construction'],['mining','Mining'],['energy','Energy & transportation']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id ? 'active' : ''} onClick={()=>filterIndustries(id as Filter)}>{label}{filter===id && <span/>}</button>)}<span className="filter-count">{filter==='all' ? '03' : '01'} INDUSTRY {filter==='all'?'WORLDS':'WORLD'}</span></div><div className={`industry-grid ${filter !== 'all' ? 'filtered' : ''}`}>{industries.filter(i=>filter==='all'||i.id===filter).map(item=><article key={item.id} className="industry-card"><div className="industry-image"><img src={item.image} alt={`${item.label}: AI-generated 2028 concept imagery`} loading="lazy" width="800" height="450"/><span className="card-number">{item.number} /</span><SaveButton id={item.id}/><span className="concept-image-label">2028 CONCEPT</span></div><button className="industry-card-link" onClick={()=>openArticle(item.id)}><div><span className="card-kicker">{item.label}</span><h3>{item.title}</h3></div><span className="round-arrow"><ArrowUpRight size={23}/></span></button><p>{item.summary}</p></article>)}</div></section>;
}
function Innovation() {
  const [tab,setTab] = useState(0); const active=innovations[tab];
  return <section id="innovation" className="innovation-section section"><div className="section-heading"><div><Label>02 / ENGINEERED FOR WHAT’S NEXT</Label><h2>THE FUTURE ISN’T FAR AWAY.<br/><span className="muted">IT’S ALREADY AT WORK.</span></h2></div><div className="innovation-counter"><span>CAT</span><sup>×</sup><IntelligenceMark/></div></div><div className="innovation-tabs" role="tablist" aria-label="Innovation topics">{innovations.map((t,i)=><button key={t.label} id={`innovation-tab-${i}`} role="tab" tabIndex={tab===i?0:-1} aria-selected={tab===i} aria-controls="innovation-panel" onKeyDown={e=>{ if (['ArrowRight','ArrowLeft','Home','End'].includes(e.key)) { e.preventDefault(); const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setTab(next);document.getElementById(`innovation-tab-${next}`)?.focus(); } }} onClick={()=>setTab(i)}><t.icon size={18}/>{t.label}<span>0{i+1}</span></button>)}</div><div className="innovation-panel" id="innovation-panel" role="tabpanel" aria-labelledby={`innovation-tab-${tab}`}><div className="innovation-visual"><img src={active.image} alt={`AI-imagined ${active.label.toLowerCase()} concept`} loading="lazy" width="1672" height="941"/><div className="vision-overlay"><span><span className="status-dot"/> VISION / 2028</span><span>CONCEPT VISUALIZATION <Plus size={13}/></span></div><div className="scan-target" aria-hidden="true"><span/><span/><span/><span/><div><Radio size={17}/> {active.label.toUpperCase()}</div></div></div><div className="innovation-copy"><span className="mono">INTELLIGENCE MEETS IRON.</span><h3>{active.title}</h3><p>{active.text}</p><div className="topic-tags">{active.tags.map(t=><span key={t}>{t}</span>)}</div><button className="text-button" onClick={()=>openArticle(active.article)}>See innovation in action <ArrowUpRight size={18}/></button><span className="innovation-note">Future-facing design. Grounded in today’s work.</span></div></div></section>;
}
function Company() {
  return <section id="company" className="company-section section"><div className="company-top"><Label light>03 / OUR PURPOSE, UNCHANGED</Label><span className="mono">SINCE 1925. ALWAYS FORWARD.</span></div><div className="company-main"><h2>WE DON’T JUST<br/>BUILD MACHINES.<br/><span>WE BUILD POSSIBILITY.</span></h2><div><p className="company-lead">Water. Energy. Roads. A place to call home.</p><p>Behind the everyday things that connect us, there are extraordinary people doing extraordinary work. We’re here to help them move the world forward.</p><button className="button dark" onClick={()=>openArticle('company')}>Meet Caterpillar <ArrowUpRight size={18}/></button></div></div><div className="purpose-grid"><div><span>01</span><h3>Built on a legacy.</h3><p>More than a century of turning big challenges into real progress.</p></div><div><span>02</span><h3>Driven by people.</h3><p>Customers, dealers, and teams with the ambition to make a difference.</p></div><div><span>03</span><h3>Focused on tomorrow.</h3><p>Technology and expertise for a changing world.</p></div></div></section>;
}
function Sustainability() {
  return <section id="sustainability" className="sustainability-section"><img src="/images/energy.webp" alt="AI-generated concept of future energy infrastructure at twilight" loading="lazy" width="1672" height="941"/><div className="sustainability-scrim"/><div className="sustainability-copy"><Label>04 / PROGRESS WITH A PURPOSE</Label><h2>A BETTER WORLD.<br/>BUILT TOGETHER.</h2><p>There’s no single path to a more sustainable future. We’re helping customers move forward—with solutions, services, and a commitment to making progress possible.</p><button className="button yellow" onClick={()=>openArticle('sustainability')}>Explore our approach <ArrowUpRight size={18}/></button></div><button className="sustainability-report" onClick={()=>openDirectory('Sustainability')}><div><span className="mono">THE PATH FORWARD</span><strong>Goals. Action. Progress.</strong><span>Explore sustainability reports & resources</span></div><ArrowUpRight size={25}/></button><span className="sustainability-disclosure mono">AI-GENERATED 2028 CONCEPT</span></section>;
}
function News() {
  return <section id="news" className="section news-section"><div className="section-heading"><div><Label>05 / PROGRESS IN MOTION</Label><h2>WHAT’S HAPPENING.</h2></div><button className="text-button" onClick={()=>openDirectory('News')}>Inside the newsroom <ArrowUpRight size={18}/></button></div><div className="news-grid">{stories.map(story=><article className="news-card" key={story.id}><button className="news-image" aria-label={`Read ${story.title}`} onClick={()=>openArticle(story.id)}><img src={story.image} alt={story.id==='autonomous-hauling'?'Concept illustration of autonomous hauling':story.id==='field-ai'?'Industrial robotics on a factory floor':'A Caterpillar manufacturing team member at work'} loading="lazy" width="800" height="450"/>{story.id==='autonomous-hauling'&&<span className="concept-image-label">CONCEPT ILLUSTRATION</span>}<span className="round-arrow"><ArrowUpRight size={20}/></span></button><div className="news-meta"><span>{story.category}</span><time>{story.date}</time></div><button className="news-title" onClick={()=>openArticle(story.id)}><h3>{story.title}</h3></button></article>)}</div><p className="snapshot-note">Real stories. Original publication dates. Content snapshot: September 18, 2026.</p></section>;
}
function CareersAndBrands() {
  const brandNames = ['Cat','Cat Financial','Cat Reman','Perkins','Solar Turbines','Progress Rail'];
  return <><section id="careers" className="careers-banner"><div><Label light>YOUR NEXT CHAPTER</Label><h2>THE FUTURE NEEDS<br/>PEOPLE LIKE YOU.</h2></div><div><p>Bring your ideas. Bring your ambition.<br/>Let’s build something that matters.</p><External className="button dark" href="https://careers.caterpillar.com/en/jobs/">Find your opportunity</External></div><span className="career-arrow" aria-hidden="true">↗</span></section><section id="brands" className="brands-section"><div className="brands-heading"><Label>ONE FAMILY. A WORLD OF POSSIBILITY.</Label><button className="text-button" onClick={()=>openDirectory('Brands')}>All brands <ArrowUpRight size={16}/></button></div><div className="brand-row">{brandNames.map((brand,i)=><button key={brand} className={`brand-word brand-${i}`} onClick={()=>{ const match=content.find(c=>c.category==='Brands'&&c.title===brand); if(match)openArticle(match.id);else openDirectory('Brands'); }}>{brand=== 'Cat'?<span className="cat-logo-text">CAT<span/></span>:brand}</button>)}</div></section></>;
}
function Footer() {
  const { agentStatus } = useSite();
  return <footer className="site-footer"><div className="footer-main"><div><img className="footer-logo" src="/images/caterpillar-logo.png" alt="Caterpillar" width="184" height="32"/><p>Building a better world.<br/>One possibility at a time.</p><button className="agent-status" onClick={()=>openModal('agent')}><span className="status-dot"/>{agentStatus} <ArrowUpRight size={13}/></button></div><div className="footer-links">{[['Explore','Company','Industries','Innovation','Sustainability'],['Connect','Careers','Investors','News','Products & services'],['Resources','Brands','Employee Resources','Suppliers & Potential Supplier Resources','Contact Us']].map(([heading,...links])=><div key={heading}><h3>{heading}</h3>{links.map(l=><button key={l} onClick={()=>{const s = ['industries','innovation','sustainability','careers','news'].find(x=>x===l.toLowerCase());if(s)navigate(s as Section);else if(l==='Employee Resources'||l.startsWith('Suppliers')||l==='Contact Us'){const item=content.find(c=>c.title===l);if(item)openArticle(item.id);else openDirectory();}else openDirectory(l);}}>{l.startsWith('Suppliers')?'Supplier resources':l}</button>)}</div>)}</div></div><div className="footer-bottom"><span>2028 DESIGN CONCEPT / INDEPENDENT & UNOFFICIAL</span><p>Caterpillar and Cat are trademarks of Caterpillar Inc. Concept imagery is AI-generated. Not affiliated with or endorsed by Caterpillar.</p><button onClick={()=>openModal('agent')}><Terminal size={13}/> Agent access</button><External href="https://www.caterpillar.com/en/legal-notices.html">Official legal notices</External></div></footer>;
}

function ModalShell({ children, title, wide=false }: { children: ReactNode; title: string; wide?: boolean }) {
  const dialog=useRef<HTMLDialogElement>(null); const {modal}=useSite();
  useEffect(()=>{const el=dialog.current;if(!el)return;const previous=document.activeElement as HTMLElement|null;if(!el.open)el.showModal();const timer=setTimeout(()=>el.querySelector<HTMLElement>('[data-autofocus]')?.focus(),30);return()=>{clearTimeout(timer);el.close();if(previous?.isConnected)previous.focus();};},[]);
  useEffect(()=>{ const el = dialog.current; if (el) { el.scrollTop=0; el.querySelector<HTMLElement>('[data-autofocus]')?.focus(); } },[modal]);
  return <dialog ref={dialog} className={`modal ${wide?'wide':''} ${modal==='guide'?'guide-modal':''}`} aria-label={title} onCancel={e=>{e.preventDefault();openModal(null);}} onClick={e=>{if(e.target===dialog.current)openModal(null);}}><div className="modal-body"><header className="modal-header"><div><IntelligenceMark/><span>{title}</span></div><button className="icon-button" aria-label="Close dialog" onClick={()=>openModal(null)}><X size={20}/></button></header>{children}</div></dialog>;
}
function ContentResult({ item, save=false }: { item: Content; save?: boolean }) {
  return <div className="result-row"><button onClick={()=>openArticle(item.id)}><span className="result-category">{item.category}</span><strong>{item.title}</strong><span>{item.summary}</span></button>{save?<SaveButton id={item.id}/>:<ArrowUpRight size={19}/>}</div>;
}
function SearchPanel() {
  const [query,setQuery]=useState('');const results=searchContent(query,10);
  return <><div className="search-input"><Search size={23}/><label htmlFor="site-search" className="sr-only">Search Caterpillar content</label><input data-autofocus id="site-search" placeholder="What are you looking for?" value={query} onChange={e=>setQuery(e.target.value)} maxLength={300}/><kbd>ESC</kbd></div><div className="panel-subheading"><span>{query?'SEARCH RESULTS':'A FEW PLACES TO START'}</span><span>{results.length} RESOURCES</span></div><div className="results-list">{results.map(item=><ContentResult key={item.id} item={item}/>)}{!results.length&&<div className="empty-state"><Search/><h3>No results for “{query}”</h3><p>Try “mining,” “careers,” “sustainability,” or “investors.”</p><button className="button yellow" onClick={()=>setQuery('')}>Explore popular resources <ArrowRight size={16}/></button></div>}</div><div className="panel-footnote"><span><Globe2 size={13}/> Source-backed, not live web search</span><span>⌘ K to search anywhere</span></div></>;
}
function DirectoryPanel() {
  const { directoryCategory }=useSite();const [query,setQuery]=useState('');
  const categories=['All','Company','Industries','Innovation','Sustainability','Brands','Careers','Investors','News','Products & services'];
  const results=(query?searchContent(query,100):content).filter(c=>directoryCategory==='All'||c.category===directoryCategory);
  return <><div className="directory-intro"><h2>YOUR WORLD.<br/>ONE PLACE TO EXPLORE.</h2><p>The information you know. A new way to find it.<br/>Explore source-backed summaries and the official Caterpillar resources.</p></div><div className="directory-controls"><div className="search-input compact"><Search size={17}/><input data-autofocus aria-label="Filter directory" placeholder="Search resources" value={query} onChange={e=>setQuery(e.target.value)} maxLength={300}/></div><label className="sr-only" htmlFor="directory-category">Resource category</label><select id="directory-category" value={directoryCategory} onChange={e=>update({directoryCategory:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="panel-subheading"><span>{directoryCategory.toUpperCase()} RESOURCES</span><span>{results.length} RESULTS</span></div><div className="directory-grid">{results.map(item=><ContentResult key={item.id} item={item} save/>)}{!results.length&&<p className="empty-state">No matching resources. Try another category or search.</p>}</div></>;
}
function ArticlePanel() {
  const {articleId}=useSite();const item=content.find(c=>c.id===articleId);if(!item)return <p>Content not found.</p>;
  return <div className="article-panel">{item.image&&<div className="article-image"><img src={item.image} alt={item.title}/>{['construction','mining','energy','autonomous-hauling'].includes(item.id)&&<span className="concept-image-label">AI-GENERATED CONCEPT ILLUSTRATION</span>}</div>}<Label>{item.category}</Label><h2>{item.title}</h2>{item.date&&<time>{item.date}</time>}<p className="article-summary">{item.summary}</p>{'tags' in item&&<div className="topic-tags">{(item.tags as string[]).map(t=><span key={t}>{t}</span>)}</div>}<div className="article-actions"><External className="button yellow" href={item.url}>Explore the official resource</External><SaveButton id={item.id} label/></div><div className="source-note"><Globe2 size={17}/><div><strong>Go straight to the source.</strong><p>This is a curated overview, not a full reproduction of the original page. Official resources open on Caterpillar’s website. Product details, availability, and company information may change.</p><a href={item.url} target="_blank" rel="noreferrer">{new URL(item.url).hostname}<ExternalLink size={12}/></a></div></div><button className="text-button" onClick={()=>{void askGuide(`Tell me about ${item.title}`);}}><IntelligenceMark/> Explore this with the guide <ArrowRight size={16}/></button></div>;
}
function inline(text: string, key: string) {
  // Providers answer in light markdown; render bold and links, leave everything else as plain text.
  const parts: ReactNode[] = []; const re = /\*\*(.+?)\*\*|\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g;
  let last = 0, m: RegExpExecArray | null, i = 0;
  while ((m = re.exec(text))) {
    if (m.index > last) parts.push(text.slice(last, m.index));
    if (m[1]) parts.push(<strong key={`${key}b${i++}`}>{m[1]}</strong>);
    else parts.push(<a key={`${key}l${i++}`} href={m[3]} target="_blank" rel="noreferrer">{m[2]}</a>);
    last = m.index + m[0].length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts.length ? parts : text;
}
function AnswerBody({ text, role, mode }: { text: string; role: string; mode?: string }) {
  if (role !== 'assistant') return <div className="message-text">{text}</div>;
  const blocks = text.split('\n\n');
  // Local retrieval composes "Title\nSummary" blocks; a live model writes prose, so only the local shape gets the titled treatment.
  if (mode === 'local') return <div className="message-text">{blocks.map((b,i)=>{const [head,...rest]=b.split('\n');return rest.length?<p key={i} className="answer-block"><strong>{head}</strong>{rest.join(' ')}</p>:<p key={i} className={i===0?'answer-lead':undefined}>{head}</p>;})}</div>;
  return <div className="message-text">{blocks.map((b,i)=><p key={i}>{b.split('\n').map((line,j)=><span key={j} className="answer-line">{inline(line,`${i}-${j}`)}</span>)}</p>)}</div>;
}
function GuidePanel() {
  const { messages,busy,aiAvailable,aiConsent }=useSite();const [query,setQuery]=useState('');const end=useRef<HTMLDivElement>(null);
  useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages,busy]);
  const submit=(e:FormEvent)=>{e.preventDefault();if(query.trim()&&!busy){void askGuide(query);setQuery('');}};
  return <><div className="guide-mode"><span><span className="status-dot"/>{aiAvailable&&aiConsent?'LIVE AI · SOURCE-GROUNDED':'SITE GUIDE · LOCAL CONTENT RETRIEVAL'}</span><button className="icon-button" aria-label="Clear conversation" disabled={busy||!messages.length} onClick={()=>update({messages:[]})}><RotateCcw size={15}/></button></div><div className="conversation" role="log" aria-label="Guide conversation" aria-live="polite">{!messages.length&&<div className="guide-welcome"><div className="guide-orbit"><IntelligenceMark/></div><Label>AN INTELLIGENT WAY IN</Label><h2>BIG QUESTIONS.<br/>BETTER STARTING POINTS.</h2><p>Explore industries, discover innovation, or find your next opportunity. Tell me where you want to go.</p><div className="guide-suggestions">{['What’s next in autonomous mining?','Explore sustainability and energy','Find engineering careers','Show investor resources'].map(q=><button key={q} onClick={()=>{void askGuide(q);}}>{q}<ArrowUpRight size={15}/></button>)}</div></div>}{messages.map(m=><div key={m.id} className={`message ${m.role}`}><div className="message-label">{m.role==='assistant'?<><IntelligenceMark/>{m.mode==='ai'?'CAT INTELLIGENCE / AI':'CAT INTELLIGENCE / SITE GUIDE'}</>:'YOU'}</div>{m.notice&&<p className="guide-notice">{m.notice}</p>}<AnswerBody text={m.text} role={m.role} mode={m.mode}/>{m.actions&&m.actions.length>0&&<div className="guide-actions"><span className="mono">I CAN DO THIS FOR YOU</span><div>{m.actions.map(a=><button key={a.kind+a.value} onClick={()=>{try{runGuideAction(a);}catch{/* full collection or unknown id: the toast already reports it */}}}>{a.label}<ArrowRight size={14}/></button>)}</div></div>}{m.sources&&m.sources.length>0&&<div className="answer-sources"><span className="mono">EXPLORE THE SOURCES</span>{m.sources.map((s,i)=><button key={s.id} onClick={()=>openArticle(s.id)}><span>0{i+1}</span>{s.title}<ArrowUpRight size={14}/></button>)}</div>}</div>)}{busy&&<div className="thinking" role="status"><span/><span/><span/> Finding a path forward…</div>}<div ref={end}/></div><div className="guide-compose">{aiAvailable&&<label className="ai-consent"><input type="checkbox" checked={aiConsent} disabled={busy} onChange={e=>update({aiConsent:e.target.checked})}/> Enable live AI: send questions and matched public content to the configured AI provider.</label>}<form onSubmit={submit}><label htmlFor="guide-question" className="sr-only">Your question</label><input id="guide-question" data-autofocus value={query} disabled={busy} onChange={e=>setQuery(e.target.value)} placeholder="Let’s find your next possibility…" maxLength={1200}/><button aria-label="Send question" disabled={busy||!query.trim()}><Send size={19}/></button></form><p>{aiAvailable&&aiConsent?'AI can make mistakes. Check the linked official sources.':'Local mode matches curated content; it is not a generative AI model.'} No account needed.</p></div></>;
}
function ShortlistPanel() {
  const {shortlist,storageAvailable}=useSite();const saved=content.filter(c=>shortlist.includes(c.id));
  function download() { const blob = new Blob([JSON.stringify({name:'My Caterpillar collection',savedAt:new Date().toISOString(),items:saved},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='caterpillar-collection.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
  return <><div className="directory-intro"><Label>YOUR IDEAS, ALL TOGETHER</Label><h2>A COLLECTION<br/>OF POSSIBILITIES.</h2><p>{saved.length} of 12 saved resources. {storageAvailable?'Stored only in this browser.':'Browser storage is unavailable; saved for this session only.'}</p></div>{saved.length?<><div className="results-list">{saved.map(item=><ContentResult key={item.id} item={item} save/>)}</div><div className="collection-actions"><button className="button yellow" onClick={download}><Download size={16}/> Export collection</button><button className="text-button" onClick={()=>openDirectory()}>Keep exploring <ArrowRight size={16}/></button></div></>:<div className="empty-state"><Bookmark size={32}/><h3>Make room for your next big idea.</h3><p>Save industries, stories, or resources using the bookmark button. Your collection is shared with connected agents.</p><button className="button yellow" onClick={()=>{openModal(null);navigate('industries');}}>Explore industries <ArrowUpRight size={17}/></button></div>}</>;
}
function AgentPanel() {
  const {agentStatus}=useSite();const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);
  const snippet=`await window.catAgent.invoke('filter_industries', { industry: 'mining' });`;
  return <div className="agent-panel"><Label>BUILT FOR PEOPLE. OPEN TO AGENTS.</Label><h2>THE SAME SITE.<br/>ANOTHER WAY IN.</h2><p>Discover, navigate, and save with structured tools—not pixel guessing. Every agent action works on the same state you see.</p><div className="agent-status-block"><span className="status-dot"/>{agentStatus}<strong>{toolManifest.length} tools</strong></div><p className="agent-explanation">Native WebMCP registers when your browser supports it. Otherwise, the browser bridge and included stdio MCP server provide access for compatible agents such as Codex. No external agent is connected automatically.</p><div className="tool-list">{toolManifest.map(t=><div key={t.name}><Terminal size={15}/><code>{t.name}</code><span>{t.annotations.readOnlyHint?'READ':'INTERACT'}</span></div>)}</div><div className="code-example"><div><span>TRY IN THE BROWSER CONSOLE</span><button className="icon-button" aria-label="Copy agent example" onClick={async()=>{try{await navigator.clipboard.writeText(snippet);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setCopyError(true);}}}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><code>{snippet}</code>{copyError&&<p>Select and copy the example manually; clipboard access is unavailable.</p>}</div><div className="source-note"><CircleHelp size={18}/><p>See <code>docs/WEBMCP.md</code> in the project for Codex setup, tool schemas, and transport details. Tools cannot purchase equipment, submit inquiries, or change your AI consent.</p></div></div>;
}
function Overlays() {
  const {modal}=useSite();if(!modal)return null;
  const titles={search:'Explore Caterpillar',guide:'Cat Intelligence',directory:'The Caterpillar world',article:'Inside Caterpillar',shortlist:'Your collection',agent:'Agent access / WebMCP'};
  return <ModalShell title={titles[modal]} wide={modal==='directory'}>{modal==='search'?<SearchPanel/>:modal==='guide'?<GuidePanel/>:modal==='directory'?<DirectoryPanel/>:modal==='article'?<ArticlePanel/>:modal==='shortlist'?<ShortlistPanel/>:<AgentPanel/>}</ModalShell>;
}
export default function App() {
  const {lastAction,modal}=useSite();const [toastVisible,setToastVisible]=useState(false);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();openModal('search');}else if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(target.tagName)&&!target.isContentEditable&&!modal){e.preventDefault();openModal('search');}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[modal]);
  useEffect(()=>{if(!lastAction)return;setToastVisible(true);const t=setTimeout(()=>setToastVisible(false),3000);return()=>clearTimeout(t);},[lastAction]);
  useEffect(()=>{const hash=location.hash.slice(1);if(['home','industries','innovation','company','sustainability','news','careers','brands'].includes(hash)){requestAnimationFrame(()=>navigate(hash as Section));}},[]);
  return <><a className="skip-link" href="#main-content">Skip to content</a><Header/><main id="main-content"><Hero/><GuideBar/><Industries/><Innovation/><Company/><Sustainability/><News/><CareersAndBrands/></main><Footer/><button className="floating-guide" onClick={()=>openModal('guide')} aria-label="Open Cat Intelligence"><IntelligenceMark/><span>Let’s build what’s next.</span><Plus size={16}/></button><div className={`toast ${toastVisible?'visible':''}`} role="status"><Check size={15}/>{lastAction}</div><Overlays/></>;
}
